# -*- coding: utf-8 -*-
"""
drawRose
"""

import turtle


def drawRose():
    turtle.fillcolor("red")
    turtle.begin_fill()
    turtle.forward(50)
    turtle.left(110)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(70)
    turtle.left(80)
    turtle.forward(45)
    turtle.left(85)
    turtle.forward(65)
    turtle.left(58)
    turtle.forward(62)
    turtle.left(100)
    turtle.forward(80)
    turtle.left(72)
    turtle.forward(95)
    turtle.left(113)
    turtle.forward(92)
    turtle.left(59)
    turtle.forward(65)
    turtle.left(48)
    turtle.forward(45)
    turtle.left(80)
    turtle.forward(100)
    turtle.left(72)
    turtle.forward(106)
    turtle.left(110)
    turtle.forward(117)
    turtle.left(60)
    turtle.forward(105)
    turtle.left(108)
    turtle.forward(105)
    turtle.left(33)
    turtle.forward(55)
    turtle.left(60)
    turtle.forward(97)
    turtle.left(110)
    turtle.forward(22)
    turtle.left(-35)
    turtle.forward(65)
    turtle.left(30)
    turtle.forward(40)
    turtle.left(25)
    turtle.forward(25)
    turtle.left(35)
    turtle.forward(30)
    turtle.left(18)
    turtle.forward(60)
    turtle.end_fill()

    turtle.left(180)
    turtle.forward(60)
    turtle.left(-20)
    turtle.forward(30)

    # turtle.fillcolor("#6BBC6F")
    turtle.fillcolor("green")
    turtle.begin_fill()
    turtle.left(25)
    turtle.forward(60)
    turtle.left(25)
    turtle.forward(40)
    turtle.left(25)
    turtle.forward(50)
    turtle.right(25)
    turtle.forward(45)
    turtle.right(18)
    turtle.forward(55)
    turtle.right(5)
    turtle.forward(40)
    turtle.right(80)
    turtle.forward(10)
    turtle.right(103)
    turtle.forward(55)
    turtle.left(10)
    turtle.forward(40)
    turtle.left(13)
    turtle.forward(30)
    turtle.left(15)
    turtle.forward(25)
    turtle.left(15)
    turtle.forward(35)
    turtle.right(25)
    turtle.forward(45)
    turtle.right(26)
    turtle.forward(60)
    turtle.right(90)
    turtle.forward(10)
    turtle.backward(10)
    turtle.right(-90)
    turtle.end_fill()

    turtle.left(180)
    turtle.forward(30)

    turtle.begin_fill()
    turtle.right(60)
    turtle.forward(15)
    turtle.left(120)
    turtle.forward(15)
    turtle.left(120)
    turtle.forward(15)
    turtle.end_fill()

    turtle.penup()
    turtle.left(180)
    turtle.left(60)
    turtle.forward(8)
    turtle.right(60)
    turtle.forward(30)
    turtle.pendown()

    turtle.begin_fill()
    turtle.left(30)
    turtle.forward(15)
    turtle.left(120)
    turtle.forward(15)
    turtle.left(120)
    turtle.forward(15)
    turtle.end_fill()

    turtle.penup()
    turtle.left(110)
    turtle.forward(43)
    turtle.pendown()

    turtle.begin_fill()
    turtle.right(90)
    turtle.forward(45)
    turtle.right(20)
    turtle.forward(70)
    turtle.right(30)
    turtle.forward(60)
    turtle.left(180)
    turtle.left(60)
    turtle.forward(55)
    turtle.right(30)
    turtle.forward(75)
    turtle.right(45)
    turtle.forward(55)
    turtle.end_fill()

    turtle.left(180)
    turtle.left(30)
    turtle.forward(50)
    turtle.left(13)
    turtle.forward(45)
    turtle.left(10)
    turtle.forward(42)
    turtle.backward(40)
    turtle.left(30)
    turtle.forward(20)
    turtle.backward(20)
    turtle.right(60)
    turtle.forward(30)
    turtle.backward(30)
    turtle.left(30)
    turtle.backward(2)
    turtle.right(10)
    turtle.backward(40)
    turtle.right(30)
    turtle.forward(30)
    turtle.backward(30)
    turtle.left(60)
    turtle.forward(30)
    turtle.right(8)
    turtle.forward(10)
    turtle.backward(10)
    turtle.left(8)
    turtle.backward(30)
    turtle.right(60)
    turtle.left(20)
    turtle.backward(30)
    turtle.left(30)
    turtle.forward(15)
    turtle.backward(15)
    turtle.right(60)
    turtle.forward(20)
    turtle.backward(20)
    turtle.left(25)
    turtle.backward(30)
    turtle.right(20)
    turtle.backward(20)
    turtle.left(180)

    turtle.begin_fill()
    turtle.right(60)
    turtle.forward(15)
    turtle.left(120)
    turtle.forward(15)
    turtle.left(120)
    turtle.forward(15)
    turtle.end_fill()

    turtle.penup()
    turtle.left(180)
    turtle.forward(35)
    turtle.pendown()

    turtle.begin_fill()
    turtle.left(40)
    turtle.forward(40)
    turtle.left(45)
    turtle.forward(45)
    turtle.left(45)
    turtle.forward(40)
    turtle.left(180)
    turtle.right(90)
    turtle.forward(30)
    turtle.left(40)
    turtle.forward(45)
    turtle.left(40)
    turtle.forward(45)
    turtle.end_fill()

    turtle.left(180)
    turtle.right(42)
    turtle.forward(50)
    turtle.left(20)
    turtle.forward(35)
    turtle.backward(20)
    turtle.left(30)
    turtle.forward(20)
    turtle.backward(20)
    turtle.right(60)
    turtle.forward(15)
    turtle.backward(15)
    turtle.left(30)
    turtle.backward(15)
    turtle.right(20)
    turtle.backward(30)
    turtle.left(30)
    turtle.forward(35)
    turtle.backward(35)
    turtle.right(60)
    turtle.forward(28)
    turtle.backward(28)
    turtle.left(30)
    turtle.backward(22)

    turtle.penup()
    turtle.right(108)
    turtle.forward(40)
    turtle.pendown()

    turtle.begin_fill()
    turtle.right(30)
    turtle.forward(10)
    turtle.left(120)
    turtle.forward(10)
    turtle.left(120)
    turtle.forward(10)
    turtle.end_fill()

    turtle.penup()
    turtle.left(120)
    turtle.left(3)
    turtle.forward(80)
    turtle.pendown()

    turtle.begin_fill()
    turtle.right(120)
    turtle.forward(15)
    turtle.right(120)
    turtle.forward(15)
    turtle.right(120)
    turtle.forward(15)
    turtle.end_fill()

    turtle.hideturtle()
    turtle.done()


def paintInit():
    width = 500
    height = 645
    x = 350
    y = 0
    turtle.setup(width, height, x, y)
    turtle.pensize(3)
    turtle.bgcolor("#FFFE88")
    turtle.penup()
    turtle.left(90)
    turtle.forward(150)
    turtle.left(-90)
    turtle.backward(50)
    turtle.pendown()
    # turtle.speed("fastest")


def main():
    paintInit()
    drawRose()


main()
